# Site settings
title: Warp10 Documentation
encoding: utf-8
email: contact@warp10.io
owner: Warp10
description: Warp10 Documentation
baseurl: ""
filename: warp10
url: "http://doc.warp10.io"
twitter_username: Warp10
pygments: true

# Build settings

# markdown: redcarpet
#redcarpet:
# extensions:  ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "lax_spacing", "smart"]

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  parse_block_html: true
  hard_wrap: false

highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

authors:
  horacio:
    display_name: Horacio Gonzalez
    gravatar: 97583a8c8a78c58ff8d2ff2bada754d7
    email: horacio.gonzalez@warp10.io
    web: http://warp10.io
    twitter: LostInBrittany
    github: LostInBrittany
    gplus: +LostInBrittany
  seb:
    display_name: Sébastien Lambour
    gravatar: 8d5d13d525423f114bb307f664ba5bbc
    email: sebastien.lambour@warp10.io
    web: http://warp10.io
    twitter: FinistSeb
    github: slambour
    gplus: +SébastienLambour29
  hbs:
    display_name: Mathias Herberts
    email: mathias.herbertsr@warp10.io
    web: http://warp10.io
    twitter: herberts
